export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
}

export const motorcycleQuestions: Question[] = [
  {
    id: 1,
    question: "You are riding under a Minnesota motorcycle instruction permit. Who must wear a helmet?",
    options: [
      "All riders under 18 and anyone with an instruction permit",
      "Only riders under 16 years of age in municipal zones",
      "Only passengers riding tandem under 18 years of age",
      "No helmet is legally required for operators with endorsements"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota law requires compliant helmets for riders under 18 and all permit holders."
  },
  {
    id: 2,
    question: "Your motorcycle has a high windshield. What eye protection is required?",
    options: [
      "None, the windshield is sufficient eye safety",
      "Approved eye protection is still legally required",
      "Goggles are required only when riding after sunset",
      "Eye protection is required only on interstate highways"
    ],
    correctAnswerIndex: 1,
    explanation: "A windshield does not exempt you from wearing approved eye protection (goggles, glasses, or visor)."
  },
  {
    id: 3,
    question: "You are riding with a motorcycle instruction permit. Which restriction is active?",
    options: [
      "No night riding and no loading of any passengers",
      "Your maximum speed is limited to 45 mph",
      "You must ride with licensed riders in your lane",
      "You must wear high-visibility lime safety vests"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota permit holders cannot ride after dark or carry passengers."
  },
  {
    id: 4,
    question: "Who is allowed to ride as a passenger on your motorcycle under a permit?",
    options: [
      "A licensed motorcycle school instructor",
      "An immediate family member over age 18",
      "Any passenger wearing a DOT-approved helmet",
      "No passenger is permitted under any circumstances"
    ],
    correctAnswerIndex: 3,
    explanation: "Minnesota motorcycle permits strictly prohibit carrying any passengers."
  },
  {
    id: 5,
    question: "At 55 mph on a clean highway, what is the minimum safe following distance?",
    options: ["A 1-second gap", "A 2-second gap", "A 3-second gap", "A 4-second gap"],
    correctAnswerIndex: 1,
    explanation: "A 2-second following distance under ideal conditions is the recommended minimum cushion."
  },
  {
    id: 6,
    question: "Riding behind a large truck, which lane position makes you most visible in their mirrors?",
    options: ["The left portion", "The right portion", "The center portion", "The shoulder edge"],
    correctAnswerIndex: 2,
    explanation: "Riding in the center of the lane makes you visible in the truck's rearview mirror."
  },
  {
    id: 7,
    question: "To stop in the shortest distance during an emergency, how should you use the brakes?",
    options: [
      "Use the rear foot brake pedal only",
      "Squeeze the front handlebar brake only",
      "Pump both brakes sequentially in a pattern",
      "Apply both brakes firmly and progressively"
    ],
    correctAnswerIndex: 3,
    explanation: "Applying both brakes simultaneously to their limits without locking them yields the quickest stop."
  },
  {
    id: 8,
    question: "How much of a motorcycle's total stopping power is generated by the front brake?",
    options: [
      "At least 70 percent of stopping power",
      "Exactly 50 percent of stopping power",
      "Around 35 percent of stopping power",
      "None; the rear brake handles all stopping"
    ],
    correctAnswerIndex: 0,
    explanation: "Forward weight transfer during deceleration increases front tire grip, allowing it to provide 70% or more of stopping force."
  },
  {
    id: 9,
    question: "To initiate a turn at speeds above 15 mph, how should you steer?",
    options: [
      "Pull back on the opposite handlebar lever",
      "Press forward on the handlebar in the turn direction",
      "Turn the handlebars in the opposite direction",
      "Shift your weight heavily without steering input"
    ],
    correctAnswerIndex: 1,
    explanation: "To turn at speed, countersteer by pressing the handlebar on the side you want to turn (press left, lean left, turn left)."
  },
  {
    id: 10,
    question: "How should you adjust the throttle mid-way through a sharp curve?",
    options: [
      "Roll off the throttle completely",
      "Pull in the clutch and coast through",
      "Apply the throttle aggressively to stand up",
      "Roll on the throttle smoothly and slightly"
    ],
    correctAnswerIndex: 3,
    explanation: "Slight acceleration through a curve stabilizes the motorcycle's suspension and maximizes grip."
  },
  {
    id: 11,
    question: "If you cannot avoid riding over a small obstacle on the road, you should:",
    options: [
      "Rise slightly off the seat and cross at a ninety-degree angle",
      "Sit back firmly and accelerate to lift the front tire",
      "Lock the brakes and slide over the obstacle sideways",
      "Squeeze the clutch and cross at a forty-five degree angle"
    ],
    correctAnswerIndex: 0,
    explanation: "Standing slightly off the seat allows your legs to absorb the shock; crossing at 90 degrees prevents tires from sliding."
  },
  {
    id: 12,
    question: "When is a wet road surface most slippery for a motorcycle?",
    options: [
      "After a heavy, two-hour rainstorm",
      "During the first few minutes of rain",
      "Just as the road begins to dry up",
      "Late at night after the rain ends"
    ],
    correctAnswerIndex: 1,
    explanation: "Initial rain mixes with accumulated oil on the road to create a slick emulsion before being washed away."
  },
  {
    id: 13,
    question: "What is the legal BAC limit for motorcycle operators age 21 or older in Minnesota?",
    options: ["0.02%", "0.05%", "0.08%", "0.10%"],
    correctAnswerIndex: 2,
    explanation: "A BAC of 0.08% or higher is the legal threshold for standard DUI arrests in Minnesota."
  },
  {
    id: 14,
    question: "Under Minnesota's Implied Consent Law, refusing a breath test results in:",
    options: [
      "A thirty-day motorcycle endorsement suspension",
      "Immediate license revocation for one year and criminal charge",
      "No penalties if you were driving safely and within limits",
      "A minor warning with a small administrative fee"
    ],
    correctAnswerIndex: 1,
    explanation: "Refusing chemical testing carries severe, immediate licensing and criminal penalties."
  },
  {
    id: 15,
    question: "Who is legally required to wear a helmet on a motorcycle in Minnesota?",
    options: [
      "All riders under 18 and all permit holders",
      "Only the operator, if under 21 years of age",
      "All passengers of any age riding tandem",
      "No one, helmets are entirely optional"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota mandates helmets for all operators and passengers under age 18, and all permit holders."
  },
  {
    id: 16,
    question: "What is the recommended formation for group riding on a highway?",
    options: [
      "Single-file line in the lane center",
      "Staggered formation in a single lane",
      "Side-by-side in pairs in one lane",
      "V-shape occupying multiple highway lanes"
    ],
    correctAnswerIndex: 1,
    explanation: "A staggered formation keeps the group together while giving each rider ample space to stop or swerve."
  },
  {
    id: 17,
    question: "When should a riding group transition from a staggered to a single-file formation?",
    options: [
      "On sharp curves, narrow roads, or exit ramps",
      "On long, straight, dry highway sections",
      "At red traffic signals or stop signs",
      "When passing through quiet neighborhoods"
    ],
    correctAnswerIndex: 0,
    explanation: "Single file is required during turns, exits, and narrow points to maximize individual maneuvering room."
  },
  {
    id: 18,
    question: "Where should an inexperienced rider be placed in a group formation?",
    options: [
      "At the very front, leading the group",
      "At the very rear, behind the sweep",
      "Directly behind the leader (second position)",
      "In the middle, sandwiched between others"
    ],
    correctAnswerIndex: 2,
    explanation: "Placing a novice in the second slot allows the leader to monitor their pace and keeps them safe."
  },
  {
    id: 19,
    question: "Under Minnesota's lane filtering law, when can a motorcycle ride between slow cars?",
    options: [
      "When traffic is under 25 mph, and bike speed is under 15 mph above traffic",
      "At any speed up to 45 mph on multi-lane interstate systems",
      "Only when riding in a group of three or more motorcycles",
      "Only when utilizing emergency hazard flashers in school zones"
    ],
    correctAnswerIndex: 0,
    explanation: "Lane filtering is legal only in slow traffic (25 mph or less) with a motorcycle speed advantage under 15 mph."
  },
  {
    id: 20,
    question: "In Minnesota, how many motorcycles are permitted to ride abreast in a single lane?",
    options: ["Only one (strict single file)", "Unlimited, if safe", "Up to three", "Up to two"],
    correctAnswerIndex: 3,
    explanation: "Minnesota law allows a maximum of two motorcycles to ride abreast in a single lane with mutual consent."
  },
  {
    id: 21,
    question: "How far ahead should a motorcycle rider scan the road for hazards?",
    options: ["At least 12 seconds", "At least 5 seconds", "Only two car lengths", "Up to the skyline"],
    correctAnswerIndex: 0,
    explanation: "Scanning 12 seconds ahead gives you plenty of time to identify and react to upcoming hazards."
  },
  {
    id: 22,
    question: "Which path through a curve provides the best line of sight and safety?",
    options: [
      "Outside-inside-outside path",
      "Inside-inside-inside path",
      "Outside-outside-outside path",
      "Weaving across both lines path"
    ],
    correctAnswerIndex: 0,
    explanation: "An outside-inside-outside line flattens the curve, improving visibility and traction."
  },
  {
    id: 23,
    question: "In Minnesota, when must a motorcycle operate with its headlights turned on?",
    options: [
      "At all times of day and night",
      "Only between sunset and sunrise",
      "Only in poor weather conditions",
      "On rural country roads only"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota law requires motorcycle headlights to be on during all operating hours to increase visibility."
  },
  {
    id: 24,
    question: "What is the safest way to ride a motorcycle across a wet steel bridge grate?",
    options: [
      "Maintain speed, ride straight, and avoid sudden inputs",
      "Squeeze the rear brake and weave through lanes",
      "Accelerate hard to cross the grate quickly",
      "Lean the motorcycle heavily and slide across"
    ],
    correctAnswerIndex: 0,
    explanation: "Keep a steady throttle and cross in a straight line without sudden braking or steering inputs."
  },
  {
    id: 25,
    question: "When carrying a passenger, how does the motorcycle's handling change?",
    options: [
      "Braking distance increases and responses are slower",
      "Braking distance is shortened significantly",
      "The motorcycle leans faster in sharp turns",
      "There is no noticeable change in stability"
    ],
    correctAnswerIndex: 0,
    explanation: "The extra passenger weight slows acceleration, increases stop distance, and alters suspension lean."
  },
  {
    id: 26,
    question: "A dog begins running towards you from the side of the road. What is the best response?",
    options: [
      "Slow down, then accelerate past the dog's intercept point",
      "Slam on both brakes to let the dog cross in front",
      "Kick at the dog with your boot to scare it back",
      "Stop the motorcycle completely and turn off the engine"
    ],
    correctAnswerIndex: 0,
    explanation: "Slowing down alters the dog's intercept calculation; accelerating then leaves it behind."
  },
  {
    id: 27,
    question: "When is the safest time to shift gears when navigating a curve?",
    options: [
      "Before entering the curve",
      "Directly at the apex of the curve",
      "Right after completing the turn",
      "Any time during the turn"
    ],
    correctAnswerIndex: 0,
    explanation: "Shift gears before entering the curve to focus on steering and throttle control."
  },
  {
    id: 28,
    question: "In Minnesota, when must you dim your motorcycle's high beams?",
    options: [
      "1,000 feet from oncoming vehicles, 200 feet from trailing vehicles",
      "500 feet from oncoming vehicles, 300 feet from trailing vehicles",
      "Only when other vehicles flashing their lights at you",
      "High beams are never dimmed on motorcycles under state law"
    ],
    correctAnswerIndex: 0,
    explanation: "Dim your high beams when oncoming traffic is within 1,000 feet or when following a vehicle within 200 feet."
  },
  {
    id: 29,
    question: "When riding a street motorcycle on gravel or loose surface roads, how should you adjust?",
    options: [
      "Reduce speed, keep body relaxed, and avoid hard braking",
      "Accelerate to hover over the gravel surface",
      "Stand fully up on the seat and lean back",
      "Keep the rear brake locked to stabilize the rear"
    ],
    correctAnswerIndex: 0,
    explanation: "Slowing down and making smooth, gentle controller inputs prevent sliding on loose soil."
  },
  {
    id: 30,
    question: "Why are the center areas of lanes often slickest during initial rain?",
    options: [
      "Engine oil drippings accumulate in the lane center",
      "Chemicals in the road paint float up",
      "Water pools deepest in the lane centers",
      "The center has smoother asphalt texturing"
    ],
    correctAnswerIndex: 0,
    explanation: "Oil leaks from cars drip in the center of the lane and rise to the surface when it rains."
  },
  {
    id: 31,
    question: "How can you warn a tailgating driver that you are about to slow down?",
    options: [
      "Flash your brake light by tapping the brake pedal slightly",
      "Wave your foot off the footpeg repeatedly",
      "Honk your horn repeatedly toward the side",
      "Swerve rapidly side to side in your lane"
    ],
    correctAnswerIndex: 0,
    explanation: "Flashing your brake light is the safest way to alert behind drivers of an upcoming deceleration."
  },
  {
    id: 32,
    question: "A motorcycle passenger should hold onto which of the following?",
    options: [
      "The operator's waist, hips, or secure handgrips",
      "The driver's shoulders or helmet visor",
      "The rear luggage rack or exhaust pipe",
      "They should keep their hands in their pockets"
    ],
    correctAnswerIndex: 0,
    explanation: "Passengers must hold onto the operator's waist/hips or designated grab bars to maintain balance."
  },
  {
    id: 33,
    question: "What does engine braking mean?",
    options: [
      "Slowing down by downshifting and releasing the clutch",
      "A catastrophic failure of the engine block",
      "Applying the rear brake only while revving",
      "Using the engine kill switch to stop the bike"
    ],
    correctAnswerIndex: 0,
    explanation: "Engine braking refers to using the engine's compression to reduce speeds by downshifting."
  },
  {
    id: 34,
    question: "What should you do before changing lanes on a motorcycle?",
    options: [
      "Check mirrors and perform a physical shoulder check",
      "Signal and merge without checking mirrors",
      "Rely entirely on your motorcycle's mirrors",
      "Honk your horn and move over immediately"
    ],
    correctAnswerIndex: 0,
    explanation: "Mirrors don't cover blind spots. Always perform a quick head check before merging."
  },
  {
    id: 35,
    question: "On a standard motorcycle, where is the clutch lever located?",
    options: [
      "On the left handlebar",
      "On the right handlebar",
      "On the left foot pedal",
      "On the right foot pedal"
    ],
    correctAnswerIndex: 0,
    explanation: "The clutch is controlled by the lever on the left handlebar."
  },
  {
    id: 36,
    question: "On a standard motorcycle, what operates the front brake?",
    options: [
      "The lever on the right handlebar",
      "The lever on the left handlebar",
      "The right foot pedal",
      "The left foot pedal"
    ],
    correctAnswerIndex: 0,
    explanation: "The front brake is squeezed using the lever on the right handlebar."
  },
  {
    id: 37,
    question: "On a standard motorcycle, what operates the rear brake?",
    options: [
      "The right foot pedal",
      "The left foot pedal",
      "The left handlebar lever",
      "The right handlebar lever"
    ],
    correctAnswerIndex: 0,
    explanation: "The rear brake is applied by pressing the pedal on the right footrest."
  },
  {
    id: 38,
    question: "On a standard motorcycle, what operates the gear shifter?",
    options: [
      "The left foot pedal",
      "The right foot pedal",
      "The left handlebar grip",
      "An automatic clutch computer"
    ],
    correctAnswerIndex: 0,
    explanation: "Gears are shifted up or down using the pedal on the left footrest."
  },
  {
    id: 39,
    question: "What should you check before riding away on a motorcycle?",
    options: [
      "That the side stand is fully retracted",
      "That the oil level is at absolute maximum",
      "That the steering lock is half engaged",
      "That the headlights are turned off"
    ],
    correctAnswerIndex: 0,
    explanation: "A down side-stand can strike the asphalt during a left turn, causing a crash."
  },
  {
    id: 40,
    question: "For safe riding, tires must have a minimum tread depth of:",
    options: ["2/32 of an inch", "1/32 of an inch", "4/32 of an inch", "No legal minimum exists"],
    correctAnswerIndex: 0,
    explanation: "Tires must have at least 2/32-inch tread to maintain grip on wet roads."
  },
  {
    id: 41,
    question: "You spot gravel or sand on the road ahead while in a curve. You should:",
    options: [
      "Slow down before reaching it and reduce your lean angle",
      "Brake hard while in the middle of the gravel",
      "Accelerate through to clear it with spinning wheels",
      "Lean extra hard to slide past the hazard"
    ],
    correctAnswerIndex: 0,
    explanation: "Reducing your speed and keeping the motorcycle as upright as possible prevents tire slips on gravel."
  },
  {
    id: 42,
    question: "What is the most effective color for motorcycle clothing to be seen by other drivers?",
    options: [
      "Bright orange, yellow, or lime green",
      "Matte black or charcoal gray",
      "Deep blue or dark navy",
      "Red or maroon leather jackets"
    ],
    correctAnswerIndex: 0,
    explanation: "Fluorescent and neon safety colors make you stand out dramatically in traffic."
  },
  {
    id: 43,
    question: "How does alcohol affect a motorcyclist's skill first?",
    options: [
      "It impairs judgment and balance",
      "It slows down physical heartbeat rates",
      "It causes rapid double vision",
      "It reduces muscular grip strength"
    ],
    correctAnswerIndex: 0,
    explanation: "Alcohol harms decision-making and inner-ear balance control before affecting physical muscles."
  },
  {
    id: 44,
    question: "To reduce exhaustion during long motorcycle rides, you should:",
    options: [
      "Take breaks of fifteen plus minutes every two hours",
      "Drink multiple high-caffeine energy drinks",
      "Drive faster to complete the route early",
      "Ride without protective safety jackets"
    ],
    correctAnswerIndex: 0,
    explanation: "Wind, noise, and vibration cause rapid fatigue. Regular rest stops are critical."
  },
  {
    id: 45,
    question: "When loading cargo on a motorcycle, where should high-weight items be placed?",
    options: [
      "Low and as close to the center of the bike as possible",
      "High up on an extended rear sissy bar rack",
      "Strapped to the front fork tubes",
      "Hung on one side saddlebag only"
    ],
    correctAnswerIndex: 0,
    explanation: "Keeping weight low and centralized helps maintain the bike's original balance."
  },
  {
    id: 46,
    question: "Wet metal construction plates can be slippery. How should you cross them?",
    options: [
      "Keep speed constant, ride straight, and do not brake",
      "Accelerate heavily to clear them before slipping",
      "Lock your rear brake to slide over",
      "Swerve slightly to look for gaps"
    ],
    correctAnswerIndex: 0,
    explanation: "Keep the motorcycle as upright as possible and maintain a steady speed over wet metal plates."
  },
  {
    id: 47,
    question: "How should a motorcycle cross railroad tracks that run parallel to your path?",
    options: [
      "Turn outward and cross at forty-five degrees or more",
      "Drive directly on top of the steel rails",
      "Slam on brakes and walk the bike across",
      "Cross them at a very sharp ten-degree angle"
    ],
    correctAnswerIndex: 0,
    explanation: "Crossing tracks at an angle of 45 to 90 degrees prevents tires from getting caught in the track lip."
  },
  {
    id: 48,
    question: "Where is high-visibility reflective tape most useful on a helmet?",
    options: [
      "On the sides, front, and back of the helmet shell",
      "Only on the underside of the chin bar",
      "Directly on the eye shield visor",
      "Reflective tape is illegal on helmets"
    ],
    correctAnswerIndex: 0,
    explanation: "Adding reflective material to your helmet increases night visibility in all directions."
  },
  {
    id: 49,
    question: "Riding in cold or damp weather can cause hypothermia. This is dangerous because it:",
    options: [
      "Slows your reflexes, impairs judgment, and causes stiffness",
      "Increases your vehicle's engine temperature",
      "Causes your tires to lose pressure rapidly",
      "Has no noticeable effect on your safe operation"
    ],
    correctAnswerIndex: 0,
    explanation: "Windchill quickly numbs fingers and slows brain reactions. Proper gear is vital."
  },
  {
    id: 50,
    question: "How should you clean a dirty polycarbonate helmet visor?",
    options: [
      "Use water, mild soap, and a soft microfiber cloth",
      "Scrub with a steel wool scouring pad and acetone",
      "Wipe dry with a rough paper towel from a gas pump",
      "Visor cleaning is completely unnecessary"
    ],
    correctAnswerIndex: 0,
    explanation: "Harsh chemicals or paper towels scratch the plastic, creating blinding glare at night."
  },
  {
    id: 51,
    question: "When parking a motorcycle in a highway stall, you should angle it so:",
    options: [
      "Its rear tire is touching or near the curb edge",
      "Its front tire is touching or near the curb edge",
      "It is completely parallel to the roadway lane",
      "It faces outward to block other parked cars"
    ],
    correctAnswerIndex: 0,
    explanation: "Parking with your rear tire against the curb keeps the bike angled out, making it visible to entering traffic."
  },
  {
    id: 52,
    question: "The 'friction zone' on a motorcycle clutch refers to:",
    options: [
      "The area of clutch travel where power begins transferring",
      "The heat generated when you lock the brakes",
      "The tire contact area rubbing against asphalt",
      "The friction inside the front fork tubes"
    ],
    correctAnswerIndex: 0,
    explanation: "Slipping the clutch slightly within the friction zone lets you control slow-speed maneuvers."
  },
  {
    id: 53,
    question: "When stopping behind a car at a red light, where should you position your bike?",
    options: [
      "To one side of the lane, leaving an escape path",
      "Directly centered behind the car's exhaust pipe",
      "With your front tire touching the car's bumper",
      "In the lane's dirtiest center roadway strip"
    ],
    correctAnswerIndex: 0,
    explanation: "Staying in the left or right portion of the lane provides an escape route if a car behind fails to stop."
  },
  {
    id: 54,
    question: "A vehicle is tailgating you closely. What is the best action?",
    options: [
      "Increase your following distance to the car ahead",
      "Brake-check the tailgater to teach them a lesson",
      "Swerve rapidly to scare the driver back",
      "Slow down to five miles per hour to block traffic"
    ],
    correctAnswerIndex: 0,
    explanation: "Increasing your front buffer means you won't have to brake hard, preventing the tailgater from hitting you."
  },
  {
    id: 55,
    question: "How often should you check your mirrors while riding?",
    options: [
      "Every few seconds, and before stopping or lane changes",
      "Only when you want to change lanes",
      "Once every ten minutes of highway travel",
      "Mirrors do not need regular monitoring"
    ],
    correctAnswerIndex: 0,
    explanation: "Constant mirror scanning keeps you aware of changing traffic conditions behind you."
  },
  {
    id: 56,
    question: "Why are wet railroad crossings particularly dangerous for motorcyclists?",
    options: [
      "Steel tracks turn highly slippery when wet",
      "Electric current in the rails can short the bike",
      "The tires are likely to blow out on contact",
      "They are never dangerous if you accelerate"
    ],
    correctAnswerIndex: 0,
    explanation: "Wet metal offers almost zero traction, so cross rails as perpendicular and smoothly as possible."
  },
  {
    id: 57,
    question: "If your motorcycle starts to wobble at high speeds, you should:",
    options: [
      "Grip handlebars firmly, ease off gas, and do not brake",
      "Slam on the front brake aggressively",
      "Accelerate hard to stabilize the front wheel",
      "Shake the handlebars to break the wobble loop"
    ],
    correctAnswerIndex: 0,
    explanation: "Slamming on brakes worsens a high-speed wobble. Hold handlebars firm, close throttle, and slow down."
  },
  {
    id: 58,
    question: "When should you adjust your speed to navigate a curve safely?",
    options: [
      "Before you enter the curve",
      "Directly at the midpoint of the curve",
      "After you exit the curve",
      "Only if you hear tires squeaking"
    ],
    correctAnswerIndex: 0,
    explanation: "Braking or downshifting inside a curve can cause slides. Always slow down before entry."
  },
  {
    id: 59,
    question: "When riding through deep sand or loose gravel, you should:",
    options: [
      "Keep speed steady and maintain a straight path",
      "Slam on high-beams and pump the brakes rapidly",
      "Swerve in wide circles to find traction",
      "Squeeze the clutch and coast through"
    ],
    correctAnswerIndex: 0,
    explanation: "Steady throttle and straight steering prevent the front wheel from digging in or sliding."
  },
  {
    id: 60,
    question: "What footwear is safest for riding a motorcycle?",
    options: [
      "Sturdy over-the-ankle leather boots",
      "Durable canvas running sneakers",
      "Comfy open-toed summer sandals",
      "Barefoot for maximum selector feel"
    ],
    correctAnswerIndex: 0,
    explanation: "Boots protect ankles from exhaust burns, flying road debris, and impact injuries."
  },
  {
    id: 61,
    question: "As a large oncoming semi-truck passes you, what force should you prepare for?",
    options: [
      "A strong gust of wind that can push you sideways",
      "A sudden vacuum that pulls you into the truck",
      "Severe electrostatic discharge from the truck's grill",
      "An automatic engine shutdown from wind gusts"
    ],
    correctAnswerIndex: 0,
    explanation: "Large commercial vehicles create powerful air turbulence that can knock a lightweight bike off track."
  },
  {
    id: 62,
    question: "How should a motorcycle's side mirrors be positioned?",
    options: [
      "To show the lane behind you and part of your shoulder",
      "To point directly down at your rear tire",
      "To face inward so you can check your helmet visor",
      "To face outward to watch other highway lanes only"
    ],
    correctAnswerIndex: 0,
    explanation: "Properly adjusted mirrors show the road behind and just a sliver of your shoulders for frame of reference."
  },
  {
    id: 63,
    question: "What must you remember about motorcycle turn signals?",
    options: [
      "Most do not cancel automatically; you must turn them off",
      "They are legally required only if traveling above 45 mph",
      "They can only flash for a maximum of five times",
      "Using signals cuts half the battery power to headlights"
    ],
    correctAnswerIndex: 0,
    explanation: "Leaving a signal blinking after a turn confuses drivers into thinking you will turn again."
  },
  {
    id: 64,
    question: "Why do some riders use high beam headlights during the daytime?",
    options: [
      "To increase their visibility to oncoming drivers",
      "To conserve the motorcycle's alternator battery",
      "To warn other vehicles that they are speeding",
      "High beams are illegal during daylight hours"
    ],
    correctAnswerIndex: 0,
    explanation: "High beams make a motorcycle stand out more in traffic during the day."
  },
  {
    id: 65,
    question: "Why should you replace a scratched helmet visor?",
    options: [
      "Scratches refract light, causing blinding glare at night",
      "Scratches can weaken the helmet's chin bar",
      "A scratched visor causes a drag of crosswinds",
      "Scratches are illegal under city ordinances"
    ],
    correctAnswerIndex: 0,
    explanation: "Scratches on visors or goggles distort incoming headlight beams, blinding the rider at night."
  },
  {
    id: 66,
    question: "Hydroplaning can occur at speeds as low as:",
    options: ["35 mph", "55 mph", "65 mph", "75 mph"],
    correctAnswerIndex: 0,
    explanation: "As speed reaches 35 mph or more, wet tires can begin to ride up on a physical layer of water."
  },
  {
    id: 67,
    question: "To apply the front brake correctly, you must:",
    options: [
      "Squeeze the handlebar lever firmly and progressively",
      "Grab the lever as fast and hard as possible",
      "Tap the lever repeatedly to trigger anti-lock",
      "Pull the lever inward using only one finger"
    ],
    correctAnswerIndex: 0,
    explanation: "Progressive squeezing transfers weight smoothly to the front tire, preventing a skid."
  },
  {
    id: 68,
    question: "What does matching engine RPMs to wheel speed during a downshift do?",
    options: [
      "Prevents the rear wheel from sliding or locking up",
      "Increases your motorcycle's fuel economy limit",
      "Extends the physical life of air filters",
      "Disengages the rear brakes automatically"
    ],
    correctAnswerIndex: 0,
    explanation: "Matching engine RPM prevents the rear tire from skidding when the clutch re-engages."
  },
  {
    id: 69,
    question: "What makes a 'head check' different from checking your mirrors?",
    options: [
      "Turning your head to look over your shoulder at lane gaps",
      "Checking the visor alignment on your helmet chin bar",
      "Waving at passing drivers to confirm they see you",
      "Measuring your helmet's internal fit clearance"
    ],
    correctAnswerIndex: 0,
    explanation: "A head check is a direct look into your blind spots that mirrors cannot display."
  },
  {
    id: 70,
    question: "What is a main hazard of an excessively loose motorcycle chain?",
    options: [
      "The chain can slip off the sprocket and lock the rear wheel",
      "It causes the spark plugs to misfire at high speeds",
      "The frame will twist out of alignment under weight",
      "It requires you to refill tire air pressures frequently"
    ],
    correctAnswerIndex: 0,
    explanation: "A loose chain can jump off the sprockets, locking up the rear tire instantly and causing a crash."
  },
  {
    id: 71,
    question: "In Minnesota, any legally required safety helmet must be certified by:",
    options: [
      "The US Department of Transportation (DOT)",
      "The local county highway patrol station",
      "The motorcycle's manufacturing brand",
      "The state department of natural resources"
    ],
    correctAnswerIndex: 0,
    explanation: "Only helmets bearing a certified DOT sticker meet the legal safety requirements in Minnesota."
  },
  {
    id: 72,
    question: "Which helmet color provides the highest visibility to other road users?",
    options: [
      "Solid white, yellow, or bright orange",
      "Flat black, graphite, or dark gray",
      "Deep forest green, brown, or olive",
      "Chrome, mirrored, or silver plating"
    ],
    correctAnswerIndex: 0,
    explanation: "White and bright fluorescent colors are easiest for other motorists to spot."
  },
  {
    id: 73,
    question: "Where is the most common location for multi-vehicle motorcycle crashes?",
    options: [
      "At public road intersections",
      "On straight rural interstate roads",
      "On winding country lanes",
      "In multi-level parking ramps"
    ],
    correctAnswerIndex: 0,
    explanation: "Intersections are high-risk zones, often because vehicles turn left across the path of an oncoming motorcycle."
  },
  {
    id: 74,
    question: "What does 'overriding your headlight' mean at night?",
    options: [
      "Your stopping distance is greater than your headlight beam distance",
      "Your headlight beam is set too high, blinding oncoming traffic",
      "The battery is generating too much power to bulb filaments",
      "You are riding with your high beams turned off in fog"
    ],
    correctAnswerIndex: 0,
    explanation: "If you cannot stop within the distance illuminated by your headlight, you are traveling too fast."
  },
  {
    id: 75,
    question: "When riding behind a bicycle in Minnesota, you should:",
    options: [
      "Maintain same safe following distance you would for any car",
      "Tailgate closely to force the bicycle onto the sidewalk",
      "Honk your horn continuously to warn them of arriving",
      "Attempt to pass them in the exact same lane abreast"
    ],
    correctAnswerIndex: 0,
    explanation: "Bicycles have equal rights on the roadway and require plenty of space buffer."
  },
  {
    id: 76,
    question: "Every motorcycle carrying a passenger must be equipped with:",
    options: [
      "Dedicated passenger footrests and safety seat straps",
      "A loud secondary communication speaker horn",
      "An automatic side stabilizer wheel system",
      "High-visibility warning signs on rear fenders"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota law requires passenger footrests if a passenger is carried on the motorcycle."
  },
  {
    id: 77,
    question: "How should you ride across painted lane markings in wet weather?",
    options: [
      "Avoid leaning or hard braking on the painted lines",
      "Speed up to cross the painted surface as fast as possible",
      "Flicker the clutch lever to slip the engine gears",
      "Slightly lock your brakes to wipe away water films"
    ],
    correctAnswerIndex: 0,
    explanation: "Wet paint is extremely slick; keep the motorcycle upright and maintain a steady speed."
  },
  {
    id: 78,
    question: "What is the most critical tire check to perform before a daily ride?",
    options: [
      "Tire air pressure using a calibrated gauge",
      "The physical age of the rubber bead lines",
      "The color of the valve stem caps",
      "The brand logos printed on the tread sidewall"
    ],
    correctAnswerIndex: 0,
    explanation: "Correct tire inflation ensures proper handling, stability, and load capacity."
  },
  {
    id: 79,
    question: "When executing a quick swerve to avoid a hazard, you must never:",
    options: [
      "Apply the brakes while actively swerving",
      "Keep your eyes focused on your target escape path",
      "Countersteer into the direction of the escape lane",
      "Keep your knees clamped tight to the fuel tank"
    ],
    correctAnswerIndex: 0,
    explanation: "Braking while swerving can lock the wheels or cause a high-side crash; swerve first, then brake."
  },
  {
    id: 80,
    question: "To make yourself more visible to cars ahead of you, you can:",
    options: [
      "Equip your motorcycle with a headlight modulator",
      "Ride with your turn signals flashing continuously",
      "Equip your wheels with blinking neon lights",
      "Turn on all emergency flashers and high beams in cities"
    ],
    correctAnswerIndex: 0,
    explanation: "A headlight modulator causes the beam to pulsate, making you stand out to oncoming drivers."
  },
  {
    id: 81,
    question: "How should a motorcycle be positioned when checking engine oil level?",
    options: [
      "Upright on level ground, not resting on the side stand",
      "Leaning heavily onto its side stand on level ground",
      "Parked downhill with steering locked to the right",
      "Dismantled with the engine block resting on its side"
    ],
    correctAnswerIndex: 0,
    explanation: "An upright position ensures an accurate dipstick or sight-glass reading."
  },
  {
    id: 82,
    question: "If your front wheel locks and begins to skid, you should immediately:",
    options: [
      "Release the front brake lever and re-apply it smoothly",
      "Squeeze the front brake lever harder to grip",
      "Shift your weight to the front fender panel",
      "Lock the rear brake to balance the skidding wheels"
    ],
    correctAnswerIndex: 0,
    explanation: "Releasing the brake instantly restores tire rotation and steering control."
  },
  {
    id: 83,
    question: "Under Minnesota law, a child riding as a passenger must:",
    options: [
      "Be physically large enough to reach passenger footrests",
      "Sit in front of the operator on the fuel tank",
      "Wear a helmet only if traveling over 55 mph",
      "Be secured with a rear-facing passenger car seat"
    ],
    correctAnswerIndex: 0,
    explanation: "To ride safely, passengers must be able to plant both feet firmly on the footpegs."
  },
  {
    id: 84,
    question: "If you detect engine oil leaking onto your motorcycle's tires, you must:",
    options: [
      "Stop riding immediately and repair the leak",
      "Drive slowly to let the heat burn the oil off",
      "Spray the tires with water and continue driving",
      "Apply sand to the tires to absorb the oil layer"
    ],
    correctAnswerIndex: 0,
    explanation: "Oil on tires destroys traction, making a crash almost certain during any turn or stop."
  },
  {
    id: 85,
    question: "If your motorcycle's throttle gets stuck open, what should you do first?",
    options: [
      "Flip the engine cut-off switch to OFF and squeeze clutch",
      "Slam on the rear brake to overcome engine speeds",
      "Squeeze the front brake lever while accelerating",
      "Shift up to the highest gear to reduce engine RPMs"
    ],
    correctAnswerIndex: 0,
    explanation: "Using the engine cut-off switch shuts down power instantly while the clutch prevents a rear-wheel skid."
  },
  {
    id: 86,
    question: "What material provides the best abrasion resistance for motorcycle apparel?",
    options: [
      "Quality leather or specialized ballistic nylon (Kevlar)",
      "Lightweight denim, cotton, or thin sweaters",
      "Synthetic nylon windbreakers and athletic wear",
      "Heavy wool coats or winter down parkas"
    ],
    correctAnswerIndex: 0,
    explanation: "Leather and specialized motorcycling synthetics protect your skin from severe road rash."
  },
  {
    id: 87,
    question: "To maintain balance during slow-speed U-turns, you should:",
    options: [
      "Counter-balance by leaning your body in the opposite direction",
      "Lean your body in the exact same direction as the bike",
      "Lock the front brake and slide the rear tire",
      "Sit back far on the fender rack to lift front wheels"
    ],
    correctAnswerIndex: 0,
    explanation: "Leaning your body away from the turn allows you to lean the motorcycle further for a tighter radius safely."
  },
  {
    id: 88,
    question: "Why should you pull in the clutch during an emergency stop?",
    options: [
      "To prevent the engine from stalling and locking the rear wheel",
      "To increase the cooling airflow to radiator fins",
      "To automatically engage the front ABS braking",
      "To lock the gearbox in neutral gear sets"
    ],
    correctAnswerIndex: 0,
    explanation: "Squeezing the clutch keeps the engine running and prevents the engine's rotation from interfering with maximum braking."
  },
  {
    id: 89,
    question: "Under Minnesota law, how does lane filtering differ from lane splitting?",
    options: [
      "Filtering is riding between slow cars; splitting is high-speed weaving",
      "They are identical and both represent high-speed interstate racing",
      "Splitting is legal for all; filtering is restricted to police",
      "They are both completely banned at all hours of the day"
    ],
    correctAnswerIndex: 0,
    explanation: "Minnesota legalized lane filtering (up to 25 mph) but kept high-speed lane splitting strictly illegal."
  },
  {
    id: 90,
    question: "Riding with a tinted helmet visor at night is:",
    options: [
      "Extremely dangerous and illegal because it reduces visibility",
      "Recommended to block glare from oncoming high beams",
      "Legal if you are traveling under 30 in bright cities",
      "Exempted for riders with prescription glasses"
    ],
    correctAnswerIndex: 0,
    explanation: "Tinted shields block too much light at night, rendering road hazards invisible."
  },
  {
    id: 91,
    question: "When starting a motorcycle on an uphill grade, you must:",
    options: [
      "Use the friction zone to transition from rear brake to throttle",
      "Dump the clutch immediately while revving the engine",
      "Roll backward to gain speed, then engage first gear",
      "Apply only the front brake and tip the bike sideways"
    ],
    correctAnswerIndex: 0,
    explanation: "Controlled clutch slipping in the friction zone holds your position on an incline before power takes over."
  },
  {
    id: 92,
    question: "When navigating a curve, where should your eyes be focused?",
    options: [
      "Through the turn, looking where you want to go",
      "Directly at the pavement one foot in front of tires",
      "At the inner yellow line on the road edge",
      "At the speedometer reading on your dashboard console"
    ],
    correctAnswerIndex: 0,
    explanation: "Motorcycles go where you look. Focus your eyes through the curve to steer a clean line."
  },
  {
    id: 93,
    question: "If your motorcycle begins to hydroplane, what should you do?",
    options: [
      "Hold the throttle steady, stay straight, and do not brake",
      "Slam on the rear brake to dig into the pavement",
      "Roll on the throttle rapidly to override the water",
      "Lean side to side to disperse water from the tread"
    ],
    correctAnswerIndex: 0,
    explanation: "Avoid any sudden throttle, braking, or steering inputs until tires regain physical pavement contact."
  },
  {
    id: 94,
    question: "What are the three standard settings on a manual motorcycle fuel valve (petcock)?",
    options: [
      "ON, OFF, and RESERVE settings",
      "ON, OFF, and CHOKE settings",
      "HIGH, MEDIUM, and LOW settings",
      "RUN, START, and STOP settings"
    ],
    correctAnswerIndex: 0,
    explanation: "The petcock valve controls fuel flow from the tank and has a reserve setting for emergencies."
  },
  {
    id: 95,
    question: "To signal a left turn with hand signals, the driver's left arm must be:",
    options: [
      "Extended straight out horizontally",
      "Raised upward at a ninety-degree angle",
      "Pointed straight down to the asphalt",
      "Waved in circular motions through the window"
    ],
    correctAnswerIndex: 0,
    explanation: "Holding your left arm straight out is the universal signal for a left turn."
  },
  {
    id: 96,
    question: "In the MSF T-CLOCS inspection checklist, what does the 'T' stand for?",
    options: [
      "Tires and Wheels inspection",
      "Throttle and Cables inspection",
      "Transmission and Clutch inspection",
      "Tools and Chain inspection"
    ],
    correctAnswerIndex: 0,
    explanation: "T-CLOCS stands for Tires/Wheels, Controls, Lights/Electrics, Oils/Fluids, Chassis, and Stands."
  },
  {
    id: 97,
    question: "Before a passenger climbs onto a motorcycle, the operator should:",
    options: [
      "Brace both feet on the ground and hold the brakes firm",
      "Stand up on the foot pegs of the motorcycle",
      "Have the engine completely shut off in neutral gear",
      "Lean the motorcycle heavily onto its side stand"
    ],
    correctAnswerIndex: 0,
    explanation: "The operator must stabilize the motorcycle to support the sudden weight shift as the passenger mounts."
  },
  {
    id: 98,
    question: "Riding on concrete pavement with rain grooves can make the bike feel:",
    options: [
      "Unstable, but it is typically safe if you maintain steady grip",
      "Highly dangerous, requiring you to exit the highway",
      "Extra grippy, allowing higher curve speeds",
      "Completely unmanageable, causing instant flat tires"
    ],
    correctAnswerIndex: 0,
    explanation: "Rain grooves can produce a weaving sensation in tires, but do not affect physical safety. Stay relaxed."
  },
  {
    id: 99,
    question: "Riding a carbureted motorcycle at very high altitudes can cause the engine to:",
    options: [
      "Run too rich, resulting in sluggish power",
      "Run too lean, leading to extreme engine overheating",
      "Stop receiving spark from the ignition plugs",
      "Increase fuel economy by up to three hundred percent"
    ],
    correctAnswerIndex: 0,
    explanation: "High altitudes have thinner oxygen levels, which makes the fuel-air mixture too rich on carbureted units."
  },
  {
    id: 100,
    question: "Using dedicated off-road knobby tires on paved highways can:",
    options: [
      "Reduce stopping traction and cause unstable highway cornering",
      "Increase your fuel efficiency and maximum top speeds",
      "Damage your motorcycle's front suspension springs",
      "Knobby tires are illegal on all paved highways under MN law"
    ],
    correctAnswerIndex: 0,
    explanation: "Knobby dirt tires have a smaller contact patch on asphalt, reducing braking and turning traction."
  }
];
